services:
  - type: web
    name: financeflow-api
    env: python
    region: singapore
    plan: free
    buildCommand: cd backend && chmod +x build.sh && ./build.sh
    startCommand: cd backend && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DEBUG
        value: False
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "localhost,127.0.0.1,financeflow-api.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: financeflow-db
          property: connectionString

databases:
  - name: financeflow-db
    databaseName: financeflow
    plan: free
    region: singapore 